version: 2

sources:
  - name: shookdw
    database: shookdw
    schema: viewpoint
    tables:
      - name: bjccd
      - name: bjcci
      - name: bjcct
      - name: bjcdm
      - name: bjcjp
      - name: brvprtimejob
      - name: jccm
      - name: APTL
      - name: APTD
      - name: ARTH
      - name: PMOI
      - name: JCOI
      - name: GLAC
      - name: GLBC
      - name: GLBD
      - name: GLAS
      - name: GLPI
  - name: kpa
    database: shookdw
    schema: kpa
    tables:
      - name: incident_notification
      - name: osha_recordable_incidents
  - name: sharepoint
    database: shookdw
    schema: sharepoint
    tables:
      - name: new_sales_data_amend
      
      