version: 2

sources:
  - name: shookdw
    database: shookdw
    schema: viewpoint
    tables:
      - name: bjccd
      - name: bjcci
      - name: bjcct
      - name: bjcdm
      - name: bjcjp
      - name: brvprtimejob
      - name: jccm
      - name: APTL
      - name: APTD
      - name: ARTH
      - name: PMOI
      - name: JCOI
      - name: GLAC
      - name: GLBC
      - name: GLBD
      - name: GLAS
      - name: GLPI
  - name: kpa
    database: shookdw
    schema: kpa
    tables:
      - name: incident_notification
      - name: osha_recordable_incidents
  - name: sharepoint
    database: shookdw
    schema: sharepoint
    tables:
      - name: new_sales_data_amend
      - name: rolling_forecast
      - name: new_sales_data_may25
      - name: new_sales_data_jun25
      - name: new_sales_data_jul25
      - name: pending_backlog_data_aug25
  - name: metadata
    database: shookdw
    schema: metadata
    tables: 
      - name: new_sales_file_control
      - name: rolling_forecast_file_control
      - name: wip_file_control
      - name: pending_backlog_file_control
  - name: P6
    database: shookdw
    schema: P6
    tables: 
      - name: ACTVCODE
      - name: PROJECT
      - name: CALENDAR
      - name: TASK
      - name: P6_JOB_HEADER
      - name: PROJWBS
      - name: P6_WEEKLY_SUBTOTALS
      - name: TASKPRED
      
      