with osha_incidents as (
    select 
        "link" link,
        "report" report,
        "report number" Report_Number,
        cast("date" as timestamp) Datetime,
        cast("updated" as timestamp) Updated,
        "updated_time" Updated_Time,
        "version" Version,
        "observer" Observer,
        "observer-emp-num" Observer_Emp_num,
        "duration" Duration_Seconds,
        "latitude" Latitude,
        "longitude" Longitude,
        "temperature" Temperature,
        "wind-speed" Wind_Speed,
        "weather" Weather,
        "8au7z4w9b4crqy0h" Completer_Information,
        "9xy8keuj7vu074vl" Description_1,
        "oshalogobserver" Completed_By,
        "oshalogobserverjob" Job,
        "oshalogobserverphone" Phone,
        to_timestamp("oshalogreportdate", 'MM/DD/YYYY') Report_Date,
        "o5s5pu9ftvlmv3ou" Employee_Information,
        "ip67xsgyui1zg6pw" Description_2,
        to_timestamp("oshalogincidentdate", 'MM/DD/YYYY') Injury_Date,
        "oshalogexistingemployee" Existing_Employee,
        "oshalogemployee" Employee,
        "oshalogemployeename" Employee_Name,
        "oshalogemptitle" Job_Title,
        "oshalogestablishment" Establishment,
        "oshalogfieldoffice" Field_Office,
        "oshaloglob" Line_of_Business,
        "oshalogclient" Company,
        "oshaloggender" Gender,
        "oshalogempstreet" Street,
        "oshalogempcity" City,
        "oshalogempstate" State,
        "oshalogempzip" Zip,
        to_timestamp("oshalogempbirthdate", 'MM/DD/YYYY') Date_of_Birth,
        to_timestamp("oshalogemphireddate", 'MM/DD/YYYY') Date_Hired,
        "ql0ouw0girm7qwth" Case_Information,
        "07tf2m5heqjb6eu5" Description_3,
        "oshalogcasenumber" Case_Number,
        "oshalogtimeworkbegan" Began_Work_Time,
        "sdkfhkeshjfnadjj" Description_4,
        "oshaloglocation" Location,
        "c9jgoa4l76xhsq5x" Description_5,
        "oshalogpredescription" Activity_Pre_Incident,
        "aj8paf2lhbwpct2d" Description_6,
        "oshalogwhathappened" Incident_Description,
        "grnt2587tf8fgezw" Description_7,
        "oshalogwhatinjury" Injury_or_Illness_Description,
        "1j5casbor32u6n9i" Description_8,
        "oshalogwhatobject" Harm_Caused_By,
        "oshalogtimeknown" Known_Time,
        "oshalogtime" Time_of_Incident,
        "oshaloginjurytype" Injury_Type,
        "oshaloginjurytypeother" Other_Illness,
        "eqlhf5fiamzg08f7" Treatment_Information,
        "oshalogdoctorname" Healthcare_Professional,
        "oshalogtreatmentaway" Treated_off_site,
        "oshalogfacilityname" Facility_Name,
        "oshalogfacilitystreet" Facility_Street,
        "oshalogfacilitycity" Facility_City,
        "oshalogfacilitystate" Facility_State,
        "oshalogfacilityzip" Facility_Zip,
        "oshaloger" Emergency_Room,
        "oshalogovernight" In_Patient,
        "ayhgh07zwls7vbyz" Outcome_1,
        "oshalogoutcome" Outcome_2,
        "oshalogreturned" Returned,
        "oshalogdeathdate" Date_of_death,
        "oshalogdaysiscalc" Days_Away_Method,
        "oshalogmanualdaysaway" Days_Away,
        "oshalogperiods" Periods_Away,
        "oshalogperiods-oshalogperiodstart" Start_1,
        "oshalogperiods-oshalogperiodend" End_1,
        "oshalogdaystransferrediscalc" Days_Transferred_Restricted,
        "oshalogmanualdaystransferred" Days,
        "oshalogperiodstransferred" Periods_Away_Restricted,
        "oshalogperiodstransferred-oshalogperiodtransferredstart" Start_2,
        "oshalogperiodstransferred-oshalogperiodtransferredend" End_2,
        "select-female" select_Female,
        "select-male" select_Male,
        "select-yes" select_Yes,
        "select-no" select_No,
        "select-days away from work" select_Days_Away_From_Work,
        "select-job transfer or restriction" select_Job_Transfer_or_Restriction,
        "select-death" select_Death,
        "select-other recordable case" select_Other_Recordable_Case,
        "select-none" select_None,
        "select-calculated" select_Calculated,
        "select-manual" select_Manual,
        "parentrepnum" Parent_Report_Number,
        "parentlink" Parent_Link,
        "surrogate" Surrogate
    from 
        {{ source('kpa', 'osha_recordable_incidents') }}
    where "link" != 'Link'
)

select * from osha_incidents